[package]
name = "monch"
version = "0.5.0"
authors = ["the Deno authors"]
documentation = "https://docs.rs/monch"
edition = "2024"
homepage = "https://deno.land/"
license = "MIT"
repository = "https://github.com/denoland/monch"
description = "Inspired by nom, but specifically for strings."
