name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
    - '*'

jobs:
  rust:
    name: string_combinators
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      CARGO_INCREMENTAL: 0
      GH_ACTIONS: 1
      RUST_BACKTRACE: full
      RUSTFLAGS: -D warnings

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
      - uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Format
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-targets --all-features --release

      - name: Build
        run: cargo build --all-targets --all-features --release
      - name: Test
        run: cargo test --all-targets --all-features --release

      - name: Publish
        if: |
          github.repository == 'denoland/string_combinators' &&
          startsWith(github.ref, 'refs/tags/')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish
